# Generated by Django 4.1.4 on 2023-01-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm1", "0003_country1_customer1_subject_subject1_teacher_teacher1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher1",
            name="subjects",
            field=models.ManyToManyField(to="orm1.subject1"),
        ),
    ]
