# Generated by Django 4.1.4 on 2023-01-18 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orm1", "0004_alter_teacher1_subjects"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer1", name="user",),
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orm1.country1"
            ),
        ),
    ]
